import type { INodeProperties } from 'n8n-workflow';

export const credTypeProperty: INodeProperties = {
    displayName: 'Authentication',
    name: 'authentication',
    type: 'options',
    default: 'basic',
    options: [
        { name: 'Basic', value: 'basic' },
        { name: 'OAuth2', value: 'oauth2' },
    ]
};

export const operationProperty: INodeProperties = {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    default: 'Read',
    noDataExpression: true,
    options: [
        { name: 'Add', value: 'Add' },
        { name: 'Approve', value: 'Approve' },
        { name: 'CreateUser', value: 'CreateUser' },
        { name: 'Custom API Call', value: 'customApiCall' },
        { name: 'Delete', value: 'Delete' },
        { name: 'MakeURL', value: 'MakeURL' },
        { name: 'Modify', value: 'Modify' },
        { name: 'ModifyOnCondition', value: 'ModifyOnCondition' },
        { name: 'Read', value: 'Read' },
        { name: 'Reject', value: 'Reject' },
        { name: 'Report', value: 'Report' },
        { name: 'Submit', value: 'Submit' },
        { name: 'Time', value: 'Time' },
        { name: 'Unapprove', value: 'Unapprove' },
        { name: 'Version', value: 'Version' },
        { name: 'Whoami', value: 'Whoami' },
    ]
};

export const resourceProperty: INodeProperties = {
    displayName: 'Resource',
    name: 'resource',
    type: 'options',
    noDataExpression: true,
    default: 'AccountingPeriod',
    options: [
        { name: "AccountingPeriod",value: "AccountingPeriod" },
        { name: "Actualcost",value: "Actualcost" },
        { name: "Address",value: "Address" },
        { name: "Agreement",value: "Agreement" },
        { name: "Agreement_to_project",value: "Agreement_to_project" },
        { name: "ApprovalLine",value: "ApprovalLine" },
        { name: "ApprovalProcess",value: "ApprovalProcess" },
        { name: "Attachment",value: "Attachment" },
        { name: "Attribute",value: "Attribute" },
        { name: "AttributeDescription",value: "AttributeDescription" },
        { name: "Attributeset",value: "Attributeset" },
        { name: "BillingSplit",value: "BillingSplit" },
        { name: "Booking",value: "Booking" },
        { name: "Booking_request",value: "Booking_request" },
        { name: "BookingByDay",value: "BookingByDay" },
        { name: "BookingType",value: "BookingType" },
        { name: "Budget",value: "Budget" },
        { name: "BudgetAllocation",value: "BudgetAllocation" },
        { name: "Category",value: "Category" },
        { name: "Category_<N>",value: "Category_<N>" },
        { name: "Ccrate",value: "Ccrate" },
        { name: "Company",value: "Company" },
        { name: "Contact",value: "Contact" },
        { name: "Costcategory",value: "Costcategory" },
        { name: "Costcenter",value: "Costcenter" },
        { name: "Costtype",value: "Costtype" },
        { name: "Currency",value: "Currency" },
        { name: "Currencyrate",value: "Currencyrate" },
        { name: "CustField",value: "CustField" },
        { name: "Customer",value: "Customer" },
        { name: "CustomerLocation",value: "CustomerLocation" },
        { name: "Customerpo",value: "Customerpo" },
        { name: "Customerpo_to_project",value: "Customerpo_to_project" },
        { name: "CustomerProspect",value: "CustomerProspect" },
        { name: "Deal",value: "Deal" },
        { name: "Dealcontact",value: "Dealcontact" },
        { name: "Dealschedule",value: "Dealschedule" },
        { name: "Department",value: "Department" },
        { name: "Entitytag",value: "Entitytag" },
        { name: "Envelope",value: "Envelope" },
        { name: "Estimate",value: "Estimate" },
        { name: "Estimateadjustment",value: "Estimateadjustment" },
        { name: "Estimateexpense",value: "Estimateexpense" },
        { name: "Estimatelabor",value: "Estimatelabor" },
        { name: "Estimatemarkup",value: "Estimatemarkup" },
        { name: "Estimatephase",value: "Estimatephase" },
        { name: "Event",value: "Event" },
        { name: "ExpensePolicy",value: "ExpensePolicy" },
        { name: "ExpensePolicyItem",value: "ExpensePolicyItem" },
        { name: "Filter",value: "Filter" },
        { name: "Filterset",value: "Filterset" },
        { name: "ForexInput",value: "ForexInput" },
        { name: "Fulfillment",value: "Fulfillment" },
        { name: "Hierarchy",value: "Hierarchy" },
        { name: "HierarchyNode",value: "HierarchyNode" },
        { name: "History",value: "History" },
        { name: "HistoryNotes",value: "HistoryNotes" }, // eslint-disable-line n8n-nodes-base/node-param-resource-with-plural-option
        { name: "ImportExport",value: "ImportExport" },
        { name: "Invoice",value: "Invoice" },
        { name: "InvoiceLayout",value: "InvoiceLayout" },
        { name: "Issue",value: "Issue" },
        { name: "IssueCategory",value: "IssueCategory" },
        { name: "IssueSeverity",value: "IssueSeverity" },
        { name: "IssueSource",value: "IssueSource" },
        { name: "IssueStage",value: "IssueStage" },
        { name: "IssueStatus",value: "IssueStatus" },
        { name: "Item",value: "Item" },
        { name: "ItemToUserLocation",value: "ItemToUserLocation" },
        { name: "Jobcode",value: "Jobcode" },
        { name: "JobCodeUsed",value: "JobCodeUsed" },
        { name: "Leave_accrual_rule",value: "Leave_accrual_rule" },
        { name: "Leave_accrual_rule_to_user",value: "Leave_accrual_rule_to_user" },
        { name: "Leave_accrual_transaction",value: "Leave_accrual_transaction" },
        { name: "LoadedCost",value: "LoadedCost" },
        { name: "Module",value: "Module" },
        { name: "Newsfeed",value: "Newsfeed" },
        { name: "NewsfeedMessage",value: "NewsfeedMessage" },
        { name: "Payment",value: "Payment" },
        { name: "Paymentterms",value: "Paymentterms" },
        { name: "Paymenttype",value: "Paymenttype" },
        { name: "Payrolltype",value: "Payrolltype" },
        { name: "PendingBooking",value: "PendingBooking" },
        { name: "Preference",value: "Preference" },
        { name: "Product",value: "Product" },
        { name: "Project",value: "Project" },
        { name: "Projectassign",value: "Projectassign" },
        { name: "ProjectAssignmentProfile",value: "ProjectAssignmentProfile" },
        { name: "Projectbillingrule",value: "Projectbillingrule" },
        { name: "Projectbillingtransaction",value: "Projectbillingtransaction" },
        { name: "ProjectBudgetGroup",value: "ProjectBudgetGroup" },
        { name: "ProjectBudgetRule",value: "ProjectBudgetRule" },
        { name: "ProjectBudgetTransaction",value: "ProjectBudgetTransaction" },
        { name: "Projectgroup",value: "Projectgroup" },
        { name: "Projectlocation",value: "Projectlocation" },
        { name: "ProjectPricing",value: "ProjectPricing" },
        { name: "ProjectStage",value: "ProjectStage" },
        { name: "Projecttask",value: "Projecttask" },
        { name: "Projecttask_type",value: "Projecttask_type" },
        { name: "Projecttaskassign",value: "Projecttaskassign" },
        { name: "ProjecttaskEstimate",value: "ProjecttaskEstimate" },
        { name: "Proposal",value: "Proposal" },
        { name: "Proposalblock",value: "Proposalblock" },
        { name: "Proxy",value: "Proxy" },
        { name: "Purchase_item",value: "Purchase_item" },
        { name: "Purchaseorder",value: "Purchaseorder" },
        { name: "Purchaser",value: "Purchaser" },
        { name: "Purchaserequest",value: "Purchaserequest" },
        { name: "Ratecard",value: "Ratecard" },
        { name: "RateCardItem",value: "RateCardItem" },
        { name: "Reimbursement",value: "Reimbursement" },
        { name: "Repeat",value: "Repeat" },
        { name: "Report",value: "Report" },
        { name: "Request_item",value: "Request_item" },
        { name: "ResourceAttachment",value: "ResourceAttachment" },
        { name: "Resourceprofile",value: "Resourceprofile" },
        { name: "Resourceprofile_type",value: "Resourceprofile_type" },
        { name: "ResourceRequest",value: "ResourceRequest" },
        { name: "ResourceRequestQueue",value: "ResourceRequestQueue" },
        { name: "Resourcesearch",value: "Resourcesearch" },
        { name: "Revenue_recognition_rule",value: "Revenue_recognition_rule" },
        { name: "Revenue_recognition_rule_amount",value: "Revenue_recognition_rule_amount" },
        { name: "Revenue_recognition_transaction",value: "Revenue_recognition_transaction" },
        { name: "RevenueContainer",value: "RevenueContainer" },
        { name: "RevenueProjection",value: "RevenueProjection" },
        { name: "RevenueStage",value: "RevenueStage" },
        { name: "Role",value: "Role" },
        { name: "Schedulebyday",value: "Schedulebyday" },
        { name: "Scheduleexception",value: "Scheduleexception" },
        { name: "Schedulerequest",value: "Schedulerequest" },
        { name: "Schedulerequest_item",value: "Schedulerequest_item" },
        { name: "Slip",value: "Slip" },
        { name: "SlipProjection",value: "SlipProjection" },
        { name: "Slipstage",value: "Slipstage" },
        { name: "SummaryView",value: "SummaryView" },
        { name: "TagGroup",value: "TagGroup" },
        { name: "TagGroupAttribute",value: "TagGroupAttribute" },
        { name: "TargetUtilization",value: "TargetUtilization" },
        { name: "Task",value: "Task" },
        { name: "TaskAdjustment",value: "TaskAdjustment" },
        { name: "TaskTimecard",value: "TaskTimecard" },
        { name: "TaxLocation",value: "TaxLocation" },
        { name: "TaxRate",value: "TaxRate" },
        { name: "Term",value: "Term" },
        { name: "ThreadedMessage",value: "ThreadedMessage" },
        { name: "Ticket",value: "Ticket" },
        { name: "Timecard",value: "Timecard" },
        { name: "Timesheet",value: "Timesheet" },
        { name: "Timetype",value: "Timetype" },
        { name: "Todo",value: "Todo" },
        { name: "Uprate",value: "Uprate" },
        { name: "User",value: "User" },
        { name: "UserLocation",value: "UserLocation" },
        { name: "UserWorkschedule",value: "UserWorkschedule" },
        { name: "Vendor",value: "Vendor" },
        { name: "Viewfilter",value: "Viewfilter" },
        { name: "Viewfilterrule",value: "Viewfilterrule" },
        { name: "WorkscheduleWorkhour",value: "WorkscheduleWorkhour" },
        { name: "Workspace",value: "Workspace" },
        { name: "Workspacelink",value: "Workspacelink" },
        { name: "Workspaceuser",value: "Workspaceuser" },
    ],
    displayOptions: {
        hide: {
            operation: ['customApiCall']
        }
    }
};

export const requestAttributesProperty: INodeProperties = {
    displayName: 'Request Attributes',
    name: 'requestAttributes',
    type: 'multiOptions',
    default: [],
    options: [
        { name: 'Enable Custom Fields', value: 'enableCustom' },
        { name: 'Exclude Flags', value: 'excludeFlags' },
        { name: 'Perform Lookup', value: 'lookup' }
    ],
    displayOptions: {
        hide: {
            operation: ['customApiCall', 'Delete', ]
        }
    }
};

export const dataProperty: INodeProperties = {
    displayName: 'Data',
    name: 'data',
    type: 'json',
    default: '{}',
    displayOptions: {
        hide: {
            operation: ['Read', 'Delete', 'customApiCall'],
        }
    }
};

export const returnProperty: INodeProperties = {
    displayName: 'Return Fields',
    name: 'return',
    placeholder: 'Add Return Field',
    hint: 'By default all fields are returned',
    type: 'fixedCollection',
    default: [],
    typeOptions: {
		multipleValues: true,
	},
    options: [
        {
            displayName: 'Return Field',
            name: 'returnField',
            values: [
                {
                    displayName: 'Field Name',
                    name: 'fieldName',
                    type: 'string',
                    default: '',
                    placeholder: 'Name of the field to return'
                },
            ],
        }
    ],
    displayOptions: {
        hide: {
            operation: ['customApiCall']
        }
    }
};